"""add_api_table

Revision ID: a9da52f46137
Revises: 6fb21bf9ba7e
Create Date: 2026-09-06 19:24:13.273344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = 'a9da52f46137'
down_revision: Union[str, Sequence[str], None] = '6fb21bf9ba7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_slug', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('api_key_raw_preview', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'grace_period', 'revoked', name='apikeystatus'), nullable=False),
    sa.Column('grace_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_slug')
    )
    op.create_index(op.f('ix_apikey_organization_id'), 'apikey', ['organization_id'], unique=False)
    op.create_index(op.f('ix_apikey_tenant_id'), 'apikey', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apikey_tenant_id'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_organization_id'), table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###
